name: Cron - NotionBird/telegram.ping

on:
  
  schedule:
    # Runs “At every minute.” (see https://crontab.guru)
    - cron: "* * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: snotion
    env:
      TGBOT_URL: ${{ secrets.TGBOT_URL }}

    steps:

      - name: Make HTTP request
        if: ${{ env.TGBOT_URL }}
        run: |
          curl ${{ env.TGBOT_URL }} \
            --fail

    steps:
      - run: echo "Run id = ${{ github.run_id }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Make HTTP request
        if: ${{ env.TGBOT_URL }}
        run: |
          curl ${{ env.TGBOT_URL }} \
            --fail
