name: Cron - TwiNotion/ping

on:
  # "Scheduled workflows run on the latest commit on the default or base branch."
  # — https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#schedule
  schedule:
    # Runs “At minute 0, 15, 30, and 45.” (see https://crontab.guru)
    - cron: "0,15,30,45 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    environment: snotion

    steps:
      - run: echo "Run id = ${{ github.run_id }}"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Make HTTP request
        if: ${{ secrets.PING_URL }}
        run: |
          curl ${{ secrets.PING_URL }} \
            --fail
